In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
##
A = np.array([[2, 3, 4],
              [10, 20, 30]])
B = np.array([[2, 3, 4],
              [10, 20, 30]], dtype = np.float32)

print("Matrix A = \n", A)
print("Shape of A =", A.shape)
print("Dtype of A =", A.dtype)

print("Matrix B = \n", B)
print("Shape of B =", B.shape)
print("Dtype of B =", B.dtype)

Matrix A = 
 [[ 2  3  4]
 [10 20 30]]
Shape of A = (2, 3)
Dtype of A = int64
Matrix B = 
 [[ 2.  3.  4.]
 [10. 20. 30.]]
Shape of B = (2, 3)
Dtype of B = float32


In [15]:
## Diagonal

a = np.array([1, 2, 3, 4])
D_1 = np.diag(a)
print("D_1 = \n", D_1)

b = np.random.randint(1, 10, 5)
print(b)
D_2 = np.diag(b)
print("D_2 = \n", D_2)

D_1 = 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[6 7 3 7 9]
D_2 = 
 [[6 0 0 0 0]
 [0 7 0 0 0]
 [0 0 3 0 0]
 [0 0 0 7 0]
 [0 0 0 0 9]]


In [17]:
## 단위행렬, Identity Matrix

I_3 = np.eye(3)
print("3 X 3 Identity Matrix = \n", I_3)

I_5 = np.eye(5)
print("5 X 5 Identity Matrix = \n", I_5)

3 X 3 Identity Matrix = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5 X 5 Identity Matrix = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
## 전치행렬, Matrix Transpose

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]], dtype = np.int64)

print("A = \n", A)
print("Transpose of A = \n", A.T)

A = 
 [[1 2 3 4]
 [5 6 7 8]]
Transpose of A = 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [21]:
## Matrix Product

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[1, 1],
              [3, 5]])

print("A * B = \n", A*B)
print("A X B = \n", np.matmul(A, B))


A * B = 
 [[ 1  2]
 [ 9 20]]
A X B = 
 [[ 7 11]
 [15 23]]
