<a href="https://colab.research.google.com/github/mjxxkxx/SeSAC/blob/main/Deep_learning_%26_pytorch_introduction%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch 설치 및 확인



In [1]:
!pip install torch

In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.4.1+cu121
False


## Pytorch Tensor

pytorch의 가장 근본이 되는 Tensor들에 대해서 배워보겠습니다.

### Tensor 만드는 법


torch.tensor(data): data는 튜플, 리스트, numpy 배열 등등임.

주요 속성들
- dtype: 데이터 타입
- device: gpu에 있는지, cpu에 있는지
- requires_grad: 이게 True면 미분값을 계산함. 아니면 하지 않음.


In [3]:
# 0-D Tensor
scalar = torch.tensor(5.0)
number = torch.tensor(1.0)
print(scalar)  # tensor(5.)
print(number) # tensor(1.)

tensor(5.)
tensor(1.)


In [6]:
# 0-D Tensor
scalar = torch.tensor(5.0)
number = torch.tensor(1.0)
print(scalar)  # tensor(5.)
print(number)  #tensor(1.)


tensor(5.)
tensor(1.)


In [7]:
vector = torch.tensor([1.0, 2.0, 3.0])
tuple_vector = torch.tensor((1,2,3))

print(vector)
print(tuple_vector)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [8]:
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
matrix2 = torch.tensor([[1, 2, 3], [3, 4, 5]])
print(matrix.shape)
print(matrix2.shape)

torch.Size([2, 2])
torch.Size([2, 3])


In [17]:
matrix2 = [[1,2,3],[3,4,5]]
lst = [matrix2, matrix2, matrix2, matrix2]

tensor_3d = torch.tensor([[[1.0], [2.0]], [[3.0], [4.0]]])
tensor_3d_2 = torch.tensor(lst) # len(lst), len(lst[0]), len(lst[0][0])
print(tensor_3d.shape)
print(tensor_3d_2.shape)

torch.Size([2, 2, 1])
torch.Size([4, 2, 3])


### torch.tensor의 주요 속성들

- tensor.shape
- tensor.size()
- tensor.dtype

In [13]:
print(vector.shape)    # torch.Size([3])
print(matrix.size())   # torch.Size([2, 2])
print(tensor_3d.shape) # torch.Size([2, 2, 1])

torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 1])


In [15]:
print(vector.dtype)    # torch.float32
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(int_tensor.dtype)  # torch.int32

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_gpu = torch.tensor([1.0, 2.0, 3.0]).to(device)
print(tensor_gpu.device)  # cuda:0 or cpu

torch.float32
torch.int32
cpu


### torch.tensor 만드는 방법

- torch.tensor(data)
- 자주 쓰는 텐서들은 만드는 함수가 있음.
  * torch.zeros(size): size 형태로 된, 0으로 된 텐서를 만듬.
  * torch.ones(size): size 형태로 된, 1로 된 텐서를 만듬.
  * torch.rand(size) / torch.randn(size) : 랜덤한 숫자로 된 텐서를 만듬. rand는 0과 1 사이에서 랜덤하게, randn은 표준정규분포(평균 0, 표준편차 1)에서 뽑아옴.
  * torch.eye(n): 대각선만 1이고 이외에는 0인 2D 텐서(행렬)을 만듬.
- 이외에도 많이 쓰이는 함수들
  * torch.arange: range() 함수와 매우 비슷하다.
  * torch.linspace(start, end, steps): start부터, end까지, steps개의 숫자를 가지는 텐서를 만듬. 이 때, 숫자들은 등간격으로 만들어짐.


In [16]:
list_tensor = torch.tensor([1, 2, 3])
tuple_tensor = torch.tensor((4, 5, 6))

zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
rand = torch.rand((2, 3))
eye = torch.eye(3)  # 3x3 Identity matrix
print(zeros)
print(ones)
print(rand)
print(eye)

normal = torch.randn((2, 3))  # Normal distribution

arange_tensor = torch.arange(start=0, end=10, step=2) # range(0, 10. 2)
linspace_tensor = torch.linspace(start=0, end=1, steps=5) # 0 0.25 0.5 0.75 1
print(arange_tensor)
print(linspace_tensor)

float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0781, 0.5872, 0.7268],
        [0.5073, 0.3363, 0.8781]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


TODO: 위 각 함수들을 torch.tensor와 파이썬 리스트 operation들을 이용하여 재구현해 보세요.

In [22]:
# write your code here
import random

def nested_list(shape, value = 0):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [value for _ in range(l)]
    else:
        l = shape[0]
        return [nested_list(shape[1:], value = value) for _ in range(l)]

def random_nested_list(shape):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [random.random() for _ in range(l)]
    else:
        l = shape[0]
        return [random_nested_list(shape[1:]) for _ in range(l)]

def randomn_nested_list(shape):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [random.gauss(0, 1) for _ in range(l)]
    else:
        l = shape[0]
        return [randomn_nested_list(shape[1:]) for _ in range(l)]

def zeros(shape):
    return torch.tensor(nested_list(shape, value = 0))

def ones(shape):
    return torch.tensor(nested_list(shape, value = 1))

def rand(shape):
    return torch.tensor(random_nested_list(shape))

def randn(shape):
    return torch.tensor(randomn_nested_list(shape))

print(nested_list((2, 3, 4), value = 0))
print(zeros((2,3,4)))
print(ones((2,3,4)))
print(rand((2,3,4)))

def eyes(n):
    lst = [[0 for i in range(n) for j in range(n)]]

    lst = []
    for i in range(n):
        tmp = []
        for j in range(n):
            tmp.append(0)
        lst.append(tmp)

    for i in range(n):  # 대각선
        lst[i][i] = 1

    return torch.tensor(lst)

[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]
tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
tensor([[[0.1591, 0.8194, 0.4731, 0.3345],
         [0.2443, 0.2277, 0.8575, 0.8895],
         [0.9861, 0.1065, 0.5945, 0.9292]],

        [[0.3164, 0.9687, 0.8571, 0.4492],
         [0.3716, 0.5599, 0.1990, 0.7955],
         [0.8698, 0.0987, 0.2315, 0.7571]]])


### torch.tensor끼리의 연산

일반적인 사칙연산, 행렬 곱(matmul), 원소간 곱 등등이 다 적용됨.

In [24]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

add = a + b  # tensor([5., 7., 9.])
sub = a - b  # tensor([-3., -3., -3.])

mul = a * b  # tensor([ 4., 10., 18.])
div = b / a  # tensor([4.0000, 2.5000, 2.0000])

exp = a ** 2  # tensor([1., 4., 9.])

In [25]:
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
'''
1 2  5 6
3 4  7 8

1 3
2 4
'''
'''
1*5 + 2*7 = 19   1*6 + 2*8 = 22
3*5 + 4*7 = 43   3*6 + 4*8 = 50
'''

matmul = torch.matmul(matrix_a, matrix_b)

# tensor([[19, 22],
#         [43, 50]])

elem_mul = matrix_a * matrix_b
# tensor([[ 5, 12],
#         [21, 32]])

transposed = torch.transpose(matrix_a, 0, 1)
# tensor([[1, 3],
#         [2, 4]])

print(torch.matmul(torch.tensor([[1],[2],[3]]), torch.tensor([[4,5,6]])))

### Broadcasting

브로드캐스팅은 서로 다른 크기를 가진 텐서들 간에 연산을 수행할 때, 자동으로 크기를 맞춰주는 PyTorch(및 NumPy)의 기능입니다. 이 기능은 명시적으로 텐서의 크기를 변환하지 않아도, 작은 크기의 텐서를 큰 크기의 텐서와 함께 연산할 수 있도록 해줍니다. Pandas나 Numpy 등에서도 자주 활용되기 때문에 알아두면 좋습니다.

브로드캐스팅 규칙:
1. 차원의 맞추기: 두 텐서의 차원(Dimension) 수가 다를 때, 차원이 작은 텐서의 앞쪽에 1을 추가하여 차원을 맞춥니다.
2. 크기 맞추기: 각 차원에서 크기가 1인 텐서는 해당 차원의 크기를 큰 텐서의 크기에 맞춰 늘릴 수 있습니다.
3. 불가능한 경우: 두 텐서가 특정 차원에서 서로 다른 크기를 가지며, 그중 하나가 1이 아니면 브로드캐스팅이 불가능하고 오류가 발생합니다.

예를 들어서,

- (2,3) 크기의 텐서에 (3,) 크기의 텐서를 더하면, (2,3) 크기의 텐서가 됩니다. 이 때 (3,) 크기의 텐서들은 첫 번째 차원에 대해서 다 더해집니다.


In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])   # Shape: (2, 3)
# b = torch.tensor([1, 2, 3])                # Shape: (3,)
# b = torch.tensor([[1, 2, 3]])              # Shape: (1, 3)
b = torch.tensor([[1, 2, 3], [1, 2, 3]])   # Shape: (2, 3)

broadcast_add = a + b  # Shape: (2, 3)
# tensor([[2, 4, 6],
#         [5, 7, 9]])

a = torch.tensor([[1], [2], [3]])  # Shape: (3, 1)
b = torch.tensor([4, 5, 6])        # Shape: (3)

b = torch.tensor([[4, 5, 6]])        # Shape: (1,3)

b = torch.tensor([[4, 5, 6],[4, 5, 6],[4, 5, 6]])        # Shape: (3,3)
a = torch.tensor([[1, 1, 1], [2, 2, 3], [3, 3, 3]])  # Shape: (3, 1)

a*b = [[4, 5, 6], [8, 10, 18], [12, 15, 18]]
# To make shapes compatible:
# a: (3, 1) -> (3, 3)
# b: (3,)   -> (1, 3) -> (3, 3)

broadcast_mul = a * b  # Shape: (3, 3)
# tensor([[ 4,  5,  6],
#         [ 8, 10, 12],
#         [12, 15, 18]])

### 이 외 tensor operation들

- Slicing / Indexing
- Reshaping
- Concatenation / Stacking

In [ ]:
# slicing / indexing
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Basic indexing
element = tensor[1, 2]  # tensor(6)

# Slicing
sub_tensor = tensor[:, 1:]  # tensor([[2, 3],
                            #         [5, 6],
                            #         [8, 9]])

# Advanced indexing with masks
mask = tensor > 5
filtered = tensor[mask]  # tensor([6, 7, 8, 9])

In [ ]:
# reshaping

tensor = torch.arange(0, 12)
reshaped_view = tensor.view(3, 4)  # tensor([[ 0,  1,  2,  3],
                                   #         [ 4,  5,  6,  7],
                                   #         [ 8,  9, 10, 11]])

reshaped_reshape = tensor.reshape(2, 6)  # tensor([[ 0,  1,  2,  3,  4,  5],
                                         #         [ 6,  7,  8,  9, 10, 11]])

# tensor.permute
tensor = torch.randn(2, 3, 4)
permuted = tensor.permute(2, 0, 1)  # Changes the order of dimensions
print(permuted.shape)  # torch.Size([4, 2, 3])


In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Concatenate along existing dimension
concat = torch.cat((a, b), dim=0)  # tensor([1, 2, 3, 4, 5, 6])

# Stack along a new dimension
stack = torch.stack((a, b), dim=0)
# tensor([[1, 2, 3],
#         [4, 5, 6]])


### 수학적 함수들

- abs, sqrt, exp, log 등 unary 함수들 (텐서 하나만을 input으로 받음): torch.abs, torch.sqrt, torch.exp, torch.log
- max, min 등 binary 함수들 (텐서 2개를 input으로 받음): torch.max, torch.min
- 차원을 하나 혹은 여럿 낮추는 Reduction Operation들: torch.sum(tensor, dim = n)


In [ ]:
a = torch.tensor([-1.0, -2.0, 3.0])

abs_a = torch.abs(a)          # tensor([1., 2., 3.])
sqrt_a = torch.sqrt(torch.abs(a))  # tensor([1., 1.4142, 1.7321])
exp_a = torch.exp(a)          # tensor([0.3679, 0.1353, 20.0855])
log_a = torch.log(torch.abs(a))    # tensor([0.0000, 0.6931, 1.0986])


In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

max_ab = torch.max(a, b)  # tensor([4., 5., 6.])
min_ab = torch.min(a, b)  # tensor([1., 2., 3.])


In [26]:
tensor = torch.tensor([[1, 2], [3, 4]])

sum_all = torch.sum(tensor)          # tensor(10)
sum_dim0 = torch.sum(tensor, dim=0)  # tensor([4, 6])
sum_dim1 = torch.sum(tensor, dim=1)  # tensor([3, 7])

mean_all = torch.mean(tensor.float())  # tensor(2.5000)

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

greater = a > b  # tensor([False, False, True])
equal = a == b   # tensor([False, True, False])


## Pytorch로 다시 해 보는 선형회귀

주어진 데이터 $(x_i, y_i)$ 에 대해서 $y=wx+b$에서, 가장 적절한 w와 b를 찾는 것이 선형회귀였음.

y = wx + b 에서, w와 b는 parameter이고 x는 입력, y는 출력임.
이 때 w랑 b를 구하기 위해서, 다음의 loss function을 최소화하는 방향으로 학습하고 싶다고 하자.

$ MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 $

원래는 저 값을 그냥 바로 식으로 계산할 수 있었지만, 언제나 그렇지는 않기 때문에 (선형회귀 외의 다른 모델들에서) 수치적으로 계산해보자.




In [ ]:
# 임의로 데이터를 한번 만들어 보자.
# True parameters
true_w = 2.0
true_b = 1.0

# Generate data
X = torch.randn(100, 1) * 10  # 100 samples, single feature
y = true_w * X + true_b + torch.randn(100, 1) * 2  # Add noise

# y[0]= true_w * X[0] + true_b + torch.randn(1, 1) * 2
# y[1]= true_w * X[1] + true_b + torch.randn(1, 1) * 2
# ...
# y[99]

# requires_grad = True로 해야 학습이 가능
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 0.005
epochs = 1000

for epoch in range(epochs):
    # Forward pass: compute predicted y
    y_pred = X * w + b

    # Compute and print loss
    loss = torch.mean((y_pred - y) ** 2)

    # Backward pass: compute gradients
    loss.backward()

    # Update parameters using gradient descent
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Zero gradients after updating
    w.grad.zero_()
    b.grad.zero_()

    if epoch % 100 == 0:
        print(f'Epoch {epoch}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')

Epoch 0: w = 2.2849, b = -1.4679, loss = 777.7333
Epoch 100: w = 2.0032, b = 0.1330, loss = 3.9277
Epoch 200: w = 2.0074, b = 0.7215, loss = 3.1670
Epoch 300: w = 2.0089, b = 0.9381, loss = 3.0639
Epoch 400: w = 2.0095, b = 1.0178, loss = 3.0500
Epoch 500: w = 2.0097, b = 1.0472, loss = 3.0481
Epoch 600: w = 2.0097, b = 1.0580, loss = 3.0478
Epoch 700: w = 2.0098, b = 1.0619, loss = 3.0478
Epoch 800: w = 2.0098, b = 1.0634, loss = 3.0478
Epoch 900: w = 2.0098, b = 1.0639, loss = 3.0478


TODO: 위 선형회귀 부분을 함수로 만들고, 다양한 하이퍼파라미터 (여기서의 hyperparameter은 learning rate 뿐임)를 바꿔가며 최적의 모델을 찾아보세요.


In [ ]:
# write your code here

### 선형회귀 조금 더 해보기


TODO: 이번에는 비슷하게, 입력이 3개이고 출력이 1개인 선형회귀를 해 보자.

$y = w_1 x_1 + w_2 x_2 + w_3 x_3 + b$

In [ ]:
# y = w1*x1 + w2 * x2 + w3 * x3 + b


NameError: name 'torch' is not defined

### 뒤에서 할 내용 미리 살짝 엿보기 - Optimizer


In [ ]:
# 이번에는 adam optimizer를 한번 사용해보자.

import torch
import math

# 임의로 데이터를 한번 만들어 보자.
# True parameters
true_w = 2.0
true_b = 1.0

# Generate data
X = torch.randn(100, 1) * 10  # 100 samples, single feature
y = true_w * X + true_b + torch.randn(100, 1) * 2  # Add noise

# requires_grad = True로 해야 학습이 가능
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# 아담 옵티마이저 하이퍼파라미터 설정
learning_rate = 0.005
epochs = 10000
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

# 아담 옵티마이저를 위한 모멘트 변수 초기화
m_w = torch.zeros_like(w)
v_w = torch.zeros_like(w)
m_b = torch.zeros_like(b)
v_b = torch.zeros_like(b)

# 아담 옵티마이저를 위한 시간 스텝 변수 초기화
t = 0

for epoch in range(1, epochs + 1):
    # Forward pass: compute predicted y
    y_pred = X * w + b

    # Compute and print loss
    loss = torch.mean((y_pred - y) ** 2)

    # Backward pass: compute gradients
    loss.backward()

    # 아담 옵티마이저 업데이트
    with torch.no_grad():
        t += 1  # 시간 스텝 증가

        # w 파라미터 업데이트
        m_w = beta1 * m_w + (1 - beta1) * w.grad
        v_w = beta2 * v_w + (1 - beta2) * (w.grad ** 2)
        # 편향 보정
        m_w_hat = m_w / (1 - beta1 ** t)
        v_w_hat = v_w / (1 - beta2 ** t)
        # 파라미터 업데이트
        w -= learning_rate * m_w_hat / (torch.sqrt(v_w_hat) + epsilon)

        # b 파라미터 업데이트
        m_b = beta1 * m_b + (1 - beta1) * b.grad
        v_b = beta2 * v_b + (1 - beta2) * (b.grad ** 2)
        # 편향 보정
        m_b_hat = m_b / (1 - beta1 ** t)
        v_b_hat = v_b / (1 - beta2 ** t)
        # 파라미터 업데이트
        b -= learning_rate * m_b_hat / (torch.sqrt(v_b_hat) + epsilon)

    # Gradients 초기화
    w.grad.zero_()
    b.grad.zero_()

    if epoch % 100 == 0:
        print(f'Epoch {epoch}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')


Epoch 100: w = 0.0580, b = 0.1627, loss = 364.6054
Epoch 200: w = 0.4848, b = 0.5600, loss = 224.0036
Epoch 300: w = 0.8526, b = 0.8696, loss = 130.7948
Epoch 400: w = 1.1600, b = 1.0872, loss = 72.6629
Epoch 500: w = 1.4081, b = 1.2152, loss = 38.8180
Epoch 600: w = 1.6004, b = 1.2650, loss = 20.5415
Epoch 700: w = 1.7433, b = 1.2549, loss = 11.4278
Epoch 800: w = 1.8446, b = 1.2065, loss = 7.2398
Epoch 900: w = 1.9132, b = 1.1396, loss = 5.4651
Epoch 1000: w = 1.9575, b = 1.0696, loss = 4.7695
Epoch 1100: w = 1.9848, b = 1.0066, loss = 4.5158
Epoch 1200: w = 2.0009, b = 0.9553, loss = 4.4291
Epoch 1300: w = 2.0100, b = 0.9169, loss = 4.4010
Epoch 1400: w = 2.0149, b = 0.8900, loss = 4.3923
Epoch 1500: w = 2.0174, b = 0.8725, loss = 4.3898
Epoch 1600: w = 2.0187, b = 0.8617, loss = 4.3890
Epoch 1700: w = 2.0193, b = 0.8554, loss = 4.3889
Epoch 1800: w = 2.0195, b = 0.8519, loss = 4.3888
Epoch 1900: w = 2.0197, b = 0.8502, loss = 4.3888
Epoch 2000: w = 2.0197, b = 0.8493, loss = 4.3888

자꾸 local minima 어딘가에 빠지는 것 같다. 이걸 수정하기 위해서, 일정 횟수 이상 바뀌지 않으면 noise를 주는 방식을 생각해보자.


In [ ]:
import torch
import math

# 임의로 데이터를 한번 만들어 보자.
# True parameters
true_w = 2.0
true_b = 1.0

# Generate data
torch.manual_seed(42)  # 재현성을 위해 시드 설정
X = torch.randn(100, 1) * 10  # 100 samples, single feature
y = true_w * X + true_b + torch.randn(100, 1) * 2  # Add noise

# requires_grad = True로 해야 학습이 가능
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# 아담 옵티마이저 하이퍼파라미터 설정
learning_rate = 0.005
epochs = 10000
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

# 아담 옵티마이저를 위한 모멘트 변수 초기화
m_w = torch.zeros_like(w)
v_w = torch.zeros_like(w)
m_b = torch.zeros_like(b)
v_b = torch.zeros_like(b)

# 아담 옵티마이저를 위한 시간 스텝 변수 초기화
t = 0


patience = 300  # 손실과 파라미터 변화가 임계값 이하로 유지되는 에포크 수
threshold_loss = 1e-4  # 손실 변화 임계값
threshold_w = 1e-4     # w 변화 임계값
threshold_b = 1e-4     # b 변화 임계값


loss_history = []
w_history = []
b_history = []

for epoch in range(1, epochs + 1):
    # Forward pass: compute predicted y
    y_pred = X * w + b

    # Compute and print loss
    loss = torch.mean((y_pred - y) ** 2)

    # Backward pass: compute gradients
    loss.backward()

    # 아담 옵티마이저 업데이트
    with torch.no_grad():
        t += 1  # 시간 스텝 증가

        # w 파라미터 업데이트
        m_w = beta1 * m_w + (1 - beta1) * w.grad
        v_w = beta2 * v_w + (1 - beta2) * (w.grad ** 2)
        # 편향 보정
        m_w_hat = m_w / (1 - beta1 ** t)
        v_w_hat = v_w / (1 - beta2 ** t)
        # 파라미터 업데이트
        w -= learning_rate * m_w_hat / (torch.sqrt(v_w_hat) + epsilon)

        # b 파라미터 업데이트
        m_b = beta1 * m_b + (1 - beta1) * b.grad
        v_b = beta2 * v_b + (1 - beta2) * (b.grad ** 2)
        # 편향 보정
        m_b_hat = m_b / (1 - beta1 ** t)
        v_b_hat = v_b / (1 - beta2 ** t)
        # 파라미터 업데이트
        b -= learning_rate * m_b_hat / (torch.sqrt(v_b_hat) + epsilon)

    # Gradients 초기화
    w.grad.zero_()
    b.grad.zero_()

    # 손실과 파라미터 값을 기록
    loss_history.append(loss.item())
    w_history.append(w.item())
    b_history.append(b.item())

    # Patience에 도달했는지 확인
    if epoch >= patience :
        # 최근 'patience' 에포크의 손실 변화 계산
        recent_losses = loss_history[-patience:]
        loss_deltas = [abs(recent_losses[i] - recent_losses[i-1]) for i in range(1, patience)]
        max_loss_delta = max(loss_deltas)

        # 최근 'patience' 에포크의 w 변화 계산
        recent_ws = w_history[-patience:]
        w_deltas = [abs(recent_ws[i] - recent_ws[i-1]) for i in range(1, patience)]
        max_w_delta = max(w_deltas)

        # 최근 'patience' 에포크의 b 변화 계산
        recent_bs = b_history[-patience:]
        b_deltas = [abs(recent_bs[i] - recent_bs[i-1]) for i in range(1, patience)]
        max_b_delta = max(b_deltas)

        # 변화가 모두 임계값 이하인 경우 노이즈 추가
        if (max_loss_delta < threshold_loss) and (max_w_delta < threshold_w) and (max_b_delta < threshold_b):
            print(f'\nEpoch {epoch}: No significant updates in the last {patience} epochs. Adding noise to parameters.')
            # 파라미터에 노이즈 추가
            noise_w = torch.randn_like(w) * 0.1
            noise_b = torch.randn_like(b) * 0.1
            w.data += noise_w
            b.data += noise_b

    if epoch % 100 == 0:
        print(f'Epoch {epoch}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')

# 최종 파라미터 출력
print(f'\nFinal Parameters: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')


Epoch 100: w = 0.8642, b = 0.2516, loss = 131.1085
Epoch 200: w = 1.2482, b = 0.6152, loss = 59.2300
Epoch 300: w = 1.5384, b = 0.8670, loss = 24.3059
Epoch 400: w = 1.7397, b = 1.0158, loss = 9.8937
Epoch 500: w = 1.8663, b = 1.0852, loss = 4.9355
Epoch 600: w = 1.9380, b = 1.1053, loss = 3.5270
Epoch 700: w = 1.9746, b = 1.1020, loss = 3.1972
Epoch 800: w = 1.9914, b = 1.0920, loss = 3.1333
Epoch 900: w = 1.9985, b = 1.0830, loss = 3.1230
Epoch 1000: w = 2.0011, b = 1.0771, loss = 3.1216
Epoch 1100: w = 2.0020, b = 1.0738, loss = 3.1215

Epoch 1143: No significant updates in the last 300 epochs. Adding noise to parameters.
Epoch 1200: w = 2.0690, b = 1.0295, loss = 3.5617
Epoch 1300: w = 2.0176, b = 1.0432, loss = 3.1449
Epoch 1400: w = 2.0055, b = 1.0597, loss = 3.1225
Epoch 1500: w = 2.0029, b = 1.0675, loss = 3.1215
Epoch 1600: w = 2.0025, b = 1.0703, loss = 3.1214
Epoch 1700: w = 2.0024, b = 1.0711, loss = 3.1214

Epoch 1719: No significant updates in the last 300 epochs. Adding 

## 딥러닝 들어가기


아래 코드는 pytorch 에서 딥러닝 모델을 짤 때, 가장 일반적인 형식이라고 할 수 있다. 각 부분에서 쓰일 함수들은 문제에 따라서 다르지만, 대개의 경우 위 내용이 크게 바뀌지 않을 것임.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np

# Seed for reproducibility
torch.manual_seed(0)
np.random.seed(0)

In [ ]:
# Generate synthetic data
num_samples = 1000
input_features = 20

# Features: random numbers
X = np.random.randn(num_samples, input_features).astype(np.float32)

# Labels: sum of features > 0 => class 1, else class 0
y = (X.sum(axis=1) > 0).astype(np.float32)

# Convert to PyTorch tensors
X_tensor = torch.from_numpy(X)
y_tensor = torch.from_numpy(y).unsqueeze(1)  # Add dimension for compatibility

# Create a dataset and data loader
dataset = TensorDataset(X_tensor, y_tensor)
batch_size = 32
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [ ]:
class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleMLP, self).__init__()
        # Define layers
        self.fc1 = nn.Linear(input_size, hidden_size)  # First fully connected layer
        self.relu = nn.ReLU()                         # ReLU activation
        self.fc2 = nn.Linear(hidden_size, output_size) # Second fully connected layer

    def forward(self, x):
        out = self.fc1(x)      # Input to first layer
        out = self.relu(out)   # Apply ReLU
        out = self.fc2(out)    # Output layer
        return out

# Hyperparameters
input_size = input_features
hidden_size = 64
output_size = 1  # Binary classification

# Instantiate the model
model = SimpleMLP(input_size, hidden_size, output_size)

# Loss function and optimizer
criterion = nn.BCEWithLogitsLoss()  # Combines a sigmoid layer and the BCELoss
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training parameters
num_epochs = 20

# Training loop
for epoch in range(num_epochs):
    for batch_X, batch_y in dataloader:
        # Forward pass
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)

        # Backward pass and optimization
        optimizer.zero_grad()  # Clear gradients
        loss.backward()        # Compute gradients
        optimizer.step()       # Update weights

    # Print loss for every epoch
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Evaluation
model.eval()

with torch.no_grad():
    outputs = model(X_tensor)
    predictions = torch.sigmoid(outputs)  # Apply sigmoid to get probabilities
    predicted_classes = (predictions >= 0.5).float()

    # Calculate accuracy
    accuracy = (predicted_classes == y_tensor).float().mean()
    print(f'Accuracy: {accuracy * 100:.2f}%')


Epoch [1/20], Loss: 0.6249
Epoch [2/20], Loss: 0.5482
Epoch [3/20], Loss: 0.4171
Epoch [4/20], Loss: 0.4820
Epoch [5/20], Loss: 0.4052
Epoch [6/20], Loss: 0.2625
Epoch [7/20], Loss: 0.3147
Epoch [8/20], Loss: 0.1852
Epoch [9/20], Loss: 0.1286
Epoch [10/20], Loss: 0.1301
Epoch [11/20], Loss: 0.0808
Epoch [12/20], Loss: 0.1353
Epoch [13/20], Loss: 0.1846
Epoch [14/20], Loss: 0.1222
Epoch [15/20], Loss: 0.0643
Epoch [16/20], Loss: 0.0972
Epoch [17/20], Loss: 0.0886
Epoch [18/20], Loss: 0.0872
Epoch [19/20], Loss: 0.1103
Epoch [20/20], Loss: 0.1142
Accuracy: 99.90%


TODO: input_size, hidden_size, learning_rate 등의 하이퍼파라미터를 바꿔 가며 최적의 모델을 찾아보세요.

In [ ]:
# write your code here